heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for servers
    default: CentOS-7
  key_name:
    type: string
    description: SSH key to connect to the servers
    default: chandra-texas-3
  flavor:
    type: string
    description: flavor used by the servers
    default: Micro-Small
  pool_id:
    type: string
    description: Pool to contact
  user_data:
    type: string
    description: Server user_data
  metadata:
    type: json
  network_id:
    type: string
#    default: a1d998bf-6a6a-4f69-b181-935213e6606b
resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      networks:
         - network: {get_param: network_id}
      user_data: {get_param: user_data}
      user_data_format: RAW


  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: 80
